version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  pg_api_data:
